import Head from "next/head";
import Questao from "../components/Questao";
import QuestaoModel from "../model/questao";
import RespostaModel from "../model/resposta";

export default function Home() {
  const questaoTeste = new QuestaoModel(1, "Melhor cor?", [
    RespostaModel.respostaErrada("Verde"),
    RespostaModel.respostaErrada("Preto"),
    RespostaModel.respostaErrada("Rosa"),
    RespostaModel.respostaCorreta("Vermelho"),
  ]);
  return (
    <>
      <Head>
        <title>Quiz Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100vh'
      }}>
      <Questao valor={questaoTeste} />
      </div>
    </>
  );
}
